export const dummyData = [
  {
    title: "restaurant",
    icon: "🍽️",
    color: "#ef4444",
    category: ["food"],
  },
  {
    title: "delivery",
    icon: "🛵",
    color: "#f97316",
    category: ["food"],
  },
  {
    title: "homemade",
    icon: "🏠",
    color: "#84cc16",
    category: ["food"],
  },
  {
    title: "sams club",
    icon: "🏬",
    color: "#2563eb",
    category: ["food", "house", "other"],
  },
  {
    title: "bravo market",
    icon: "🛒",
    color: "#16a34a",
    category: ["food"],
  },
  {
    title: "walmart",
    icon: "🏪",
    color: "#1d4ed8",
    category: ["food", "house", "other"],
  },
  {
    title: "gas",
    icon: "⛽",
    color: "#eab308",
    category: ["transport"],
  },
  {
    title: "car repair",
    icon: "🔧",
    color: "#6b7280",
    category: ["transport"],
  },
  {
    title: "uber",
    icon: "🚕",
    color: "#000000",
    category: ["transport"],
  },
  {
    title: "beer",
    icon: "🍺",
    color: "#fbbf24",
    category: ["drinks"],
  },
  {
    title: "rum",
    icon: "🥃",
    color: "#92400e",
    category: ["drinks"],
  },
  {
    title: "whiskey",
    icon: "🥃",
    color: "#78350f",
    category: ["drinks"],
  },
  {
    title: "mortgage",
    icon: "🏡",
    color: "#14b8a6",
    category: ["house"],
  },
  {
    title: "electricity",
    icon: "⚡",
    color: "#ffc00a",
    category: ["bills"],
  },
  {
    title: "internet",
    icon: "🌐",
    color: "#3b82f6",
    category: ["bills"],
  },
  {
    title: "cel tmobil",
    icon: "🌐",
    color: "#cc16cc",
    category: ["bills"],
  },
  {
    title: "car insurance",
    icon: "🚗",
    color: "#22c55e",
    category: ["bills"],
  },
  {
    title: "water",
    icon: "🚰",
    color: "#38bdf8",
    category: ["bills"],
  },
  {
    title: "electronics",
    icon: "📱",
    color: "#6366f1",
    category: ["amazon", "other"],
  },
  {
    title: "house repairs",
    icon: "🧼",
    color: "#10b981",
    category: ["amazon", "house"],
  },
  {
    title: "clothing",
    icon: "🧥",
    color: "#ec4899",
    category: ["clothes", "amazon"],
  },
  {
    title: "books",
    icon: "📚",
    color: "#a855f7",
    category: ["amazon", "other"],
  },
  {
    title: "clothes",
    icon: "👕",
    color: "#ec4899",
    category: ["clothes", "amazon"],
  },
  {
    title: "games",
    icon: "🎮",
    color: "#f59e0b",
    category: ["amazon", "other"],
  },
  {
    title: "send money",
    icon: "💸",
    color: "#f43f5e",
    category: ["other"],
  },
  {
    title: "bitcoin",
    icon: "₿",
    color: "#f7931a",
    category: ["crypto"],
  },
  {
    title: "ethereum",
    icon: "Ξ",
    color: "#627eea",
    category: ["crypto"],
  },
  {
    title: "trash tickets",
    icon: "🎟️",
    color: "#22c55e ",
    category: ["house"],
  },
  {
    title: "decoration",
    icon: "🖼️",
    color: "#a855f7",
    category: ["house"],
  },
  {
    title: "furniture",
    icon: "🪑",
    color: "#8b5cf6",
    category: ["house", "amazon"],
  },
  {
    title: "utils ",
    icon: "📌",
    color: "#9ca3af",
    category: ["house", "amazon"],
  },
];
